In [1]:
import sys
sys.path.append("../src")

In [ ]:
from db_connection import DatabaseConnector
from queries import NBAReceiverQuaries
from data_loader import NBADataLoader

In [3]:
db = DatabaseConnector(env_path="../.env")
engine = db.create_connection()

In [4]:
loader = NBADataLoader(engine)

df_agility = loader.load_agility_data(NBAReceiverQuaries.query_agility)
df_intrinsic = loader.load_intrinsic_data(NBAReceiverQuaries.query_intrinsic)

In [5]:
df_agility.head()

  season_years period_group  player_id               fullname   agility
0    2020-2021  past_period       1036          Stephen Curry  0.400000
1    2020-2021  past_period       2561         Damian Lillard  0.370000
2    2020-2021  past_period        120  Giannis Antetokounmpo  0.341564
3    2020-2021  past_period       1480          Julius Randle  0.324000
4    2020-2021  past_period       3935            Joel Embiid  0.300000

In [6]:
df_agility.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   season_years  41 non-null     object
 1   period_group  41 non-null     object
 2   player_id     41 non-null     int64
 3   fullname      41 non-null     object
 4   agility       41 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 1.7+ KB

In [7]:
df_intrinsic.head()

,season_years,period_group,champion_club,player_id,fullname,age,experience,intrinsic_talent
0,2020-2021,past_period,Atlanta Hawks,727,Clint Capela,26.0,6,0.230769
1,2020-2021,past_period,Atlanta Hawks,898,John Collins,23.0,3,0.130435
2,2020-2021,past_period,Atlanta Hawks,3845,Kris Dunn,26.0,4,0.153846
3,2020-2021,past_period,Atlanta Hawks,4013,Bruno Fernando,22.0,1,0.045455
4,2020-2021,past_period,Atlanta Hawks,3205,Kevin Huerter,22.0,2,0.090909

In [8]:
df_intrinsic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   season_years      182 non-null    object
 1   period_group      182 non-null    object
 2   champion_club     182 non-null    object
 3   player_id         182 non-null    int64
 4   fullname          182 non-null    object
 5   age               182 non-null    float64
 6   experience        182 non-null    int64
 7   intrinsic_talent  182 non-null    float64
dtypes: float64(2), int64(2), object(4)
memory usage: 11.5+ KB